apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ai-service","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"ai-service"}}}
  creationTimestamp: "2025-12-16T10:45:20Z"
  name: ai-service
  namespace: default
  resourceVersion: "13684"
  uid: adddddf2-396b-4b6a-af0c-48772af0b506
spec:
  clusterIP: 10.100.201.191
  clusterIPs:
  - 10.100.201.191
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ai-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
