apiVersion: v1
kind: Service
metadata:
  name: conversation-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3004
    protocol: TCP
  selector:
    app: conversation-service
