apiVersion: v1
kind: Service
metadata:
  name: insight-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
  selector:
    app: insight-service
