apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3005
    protocol: TCP
  selector:
    app: quiz-service
