apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
      - name: quiz-service
        image: songhyunkwang/pai-service-quiz:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: DB_HOST
          value: postgres
        - name: REDIS_HOST
          value: redis
        envFrom:
        - secretRef:
            name: quiz-secrets
